Repository IyaadArshad/cs-cc25, pull requests merged in 2025-02, with the labels that each got.

#2 added metadata and new favicon
  app/favicon.ico
  app/layout.tsx
Labels: size/XS

#5 Adding image functionality
  app/case/discover.tsx
Labels: size/M

#25 push working chat
  app/case/chat.tsx
Labels: size/L
