Repository IyaadArshad/cs-cc25, pull requests merged in 2025-04, with the labels that each got.

#28 Fixing image problems
  app/case/apps.tsx
  app/case/discoverData.ts
  public/img/apps/TAQA.png
  public/img/apps/abuDhabiDistributionCompany.png
  public/img/apps/abuDhabiPolice.png
  public/img/apps/careem.png
  public/img/apps/darb.png
  public/img/apps/entertainer.png
  public/img/apps/tripadvisor.png
  public/img/apps/visitAbuDhabi.png
  public/img/apps/zomato.png
  public/img/discover/localMarketsAndStores/YasMall.png
  public/img/discover/localMarketsAndStores/worldTradeCenterMall.png
  public/img/discover/localMarketsAndStores/wtcmall.jpg
  public/img/discover/localMarketsAndStores/yasmall.jpg
Labels: size/S

#31 update TAQA card content and external link for accuracy
  app/case/apps.tsx
Labels: size/XS

#34 Culture screen updtes
  app/case/culture.tsx
  app/case/cultureData.tsx
  next.config.ts
Labels: size/XL

#37 Fix article link and update image source; enhance source and date dis…
  app/api/v1/feed/content.ts
  app/case/home.tsx
Labels: size/XL
